## Ubuntu: ~100MB, basic+zsh: ~195MB, cbuild: ~288MB
FROM ubuntu:24.04

## Avoid prompts from apt
ENV DEBIAN_FRONTEND=noninteractive

## Required packages (also, Combining Commands to Save Space)
RUN apt update \
    && apt install -y \
    ## Sometimes Error-prone: --no-install-recommends
    # && apt install -y --no-install-recommends \
    curl \
    git \
    vim \
    tree \
    ## C Build
    build-essential \
    # gcc \
    # g++ \
    # make \
    ## <Optional> CMake
    # cmake \
    ## <Optional> Zsh
    zsh \
    fonts-powerline

## Space Optimization
# && rm -rf /var/lib/apt/lists/*

## Working Directory
WORKDIR /root

## <Optional> Oh-My-Zsh (& Configuration)
RUN sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
COPY ./installed/zshrc /root/.zshrc

## <Optional> Set Zsh as default shell
RUN chsh -s $(which zsh)


## CMD
CMD [ "zsh" ]

## Build & Run
## $ docker build -t cbuild-ubuntu:24.04 -f Dockerfile.cbuild .
## $ docker run -it -h cbuild-ubuntu -v ./workdir:/root/workdir --name cbuild-ubuntu cbuild-ubuntu:24.04